minify_css:
    #- from: ["prj/static/css/style.css", "prj/static/css/custom.css"]
    #  to: "prj/static/css/all.min.css"

minify_js:
    #- from: "prj/static/js/script.js"
    #  to: "prj/static/js/script.min.js"

crontabs:
    #- name: 'calling /bin/true'
    #  crontab: '* 10 * * * /bin/true'
    #- name: 'base path test'
    #  crontab: '* 20 * * * {base_path}/manage.py'
    #- name: 'current project path test'
    #  crontab: '* 20 * * * {project_path}/manage.py'
